{
  "name": "complex-solution",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "eslint src --ext .js,.jsx,.ts,.tsx || echo 'ESLint not configured'",
    "lint:fix": "eslint src --ext .js,.jsx,.ts,.tsx --fix || echo 'ESLint not configured'",
    "type-check": "tsc --noEmit || echo 'TypeScript not configured'",
    "build:prod": "cross-env NODE_ENV=production npm run build",
    "deploy": "npm run build && deploy.bat",
    "deploy:ps": "npm run build && powershell -ExecutionPolicy Bypass -File deploy.ps1",
    "deploy:manual": "npm run build && echo 'Build completed. Use deploy.bat or deploy.ps1 for deployment.'",
    "preview": "npm run build && npx serve -s build",
    "clean": "rimraf build node_modules package-lock.json && npm install"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "cross-env": "^7.0.3",
    "rimraf": "^5.0.5",
    "serve": "^14.2.1"
  },
  "homepage": "https://test.complex-solutions.uz"
}